title: Yinrong Zhang's Homepage
page-top-title: Yinrong Zhang
top-section-bg-text: Life is a story                  written beneath the stars.
home-subtitle: Yinrong Zhang|张荫榕
copyright-text: '&copy; Yinrong Zhang 2023-2025. All Rights Reserved.'
